MODULE_NAME := sensor_sc430ai_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc430ai

SRCS := $(DIR)/sc430ai/sc430ai.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

