MODULE_NAME := sensor_sc3336_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc3336

SRCS := $(DIR)/sc3336/sc3336.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

