MODULE_NAME := sensor_mis2003_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)

SRCS := $(DIR)/mis2003/mis2003.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
