MODULE_NAME := sensor_sc5239_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc5239

SRCS := $(DIR)/sc5239/sc5239.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

