MODULE_NAME := sensor_sp1405_t31
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sp1405

SRCS := $(DIR)/sp1405/sp1405.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

