MODULE_NAME := sensor_gc4023_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/gc4023

SRCS := $(DIR)/gc4023/gc4023.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

