MODULE_NAME := sensor_sc4335_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc4335

SRCS := $(DIR)/sc4335/sc4335.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

