MODULE_NAME := sensor_sc031gs_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc031gs

SRCS := $(DIR)/sc031gs/sc031gs.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

