MODULE_NAME := sensor_gc2083_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/gc2083

SRCS := $(DIR)/gc2083/gc2083.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

