MODULE_NAME := sensor_sc2210_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc2210

SRCS := $(DIR)/sc2210/sc2210.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

