MODULE_NAME := sensor_gc2093_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/gc2093

SRCS := $(DIR)/gc2093/gc2093.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

