include $(src)/sensors/$(SOC)/jxf22/Kbuild
include $(src)/sensors/$(SOC)/jxf23/Kbuild
include $(src)/sensors/$(SOC)/jxf28/Kbuild
include $(src)/sensors/$(SOC)/jxh42/Kbuild
include $(src)/sensors/$(SOC)/jxh61/Kbuild
include $(src)/sensors/$(SOC)/jxh62/Kbuild
include $(src)/sensors/$(SOC)/jxh65/Kbuild
include $(src)/sensors/$(SOC)/jxk02/Kbuild
include $(src)/sensors/$(SOC)/jxv01/Kbuild

