MODULE_NAME := sensor_os04l10_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)

SRCS := $(DIR)/os04l10/os04l10.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

