MODULE_NAME := sensor_ov2745_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/ov2745

SRCS := $(DIR)/ov2745/ov2745.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

