MODULE_NAME := sensor_sc301IoT_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc301IoT

SRCS := $(DIR)/sc301IoT/sc301IoT.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

