MODULE_NAME := sensor_sc5336_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc5336

SRCS := $(DIR)/sc5336/sc5336.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

