MODULE_NAME := sensor_sc4210_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc4210

SRCS := $(DIR)/sc4210/sc4210.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

