MODULE_NAME := sensor_c23a98_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/c23a98

SRCS := $(DIR)/c23a98/c23a98.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

