MODULE_NAME := sensor_sc2239p_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc2239p

SRCS := $(DIR)/sc2239p/sc2239p.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

