MODULE_NAME := sensor_sc5338_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc5338

SRCS := $(DIR)/sc5338/sc5338.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

