MODULE_NAME := sensor_sc233a_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc233a

SRCS := $(DIR)/sc233a/sc233a.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

