MODULE_NAME := sensor_os04a10_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/os04a10

SRCS := $(DIR)/os04a10/os04a10.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

