MODULE_NAME := sensor_ov8856_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/ov8856

SRCS := $(DIR)/ov8856/ov8856.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

