MODULE_NAME := sensor_cv5001_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/cv5001

SRCS := $(DIR)/cv5001/cv5001.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

