MODULE_NAME := sensor_os04c10_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/os04c10

SRCS := $(DIR)/os04c10/os04c10.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

