MODULE_NAME := sensor_cv3001_t31
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/cv3001

SRCS := $(DIR)/cv3001/cv3001.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

