MODULE_NAME := sensor_os02g10_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/os02g10

SRCS := $(DIR)/os02g10/os02g10.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

