MODULE_NAME := sensor_jxf37p_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/jxf37p

SRCS := $(DIR)/jxf37p/jxf37p.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

