MODULE_NAME := sensor_cv4001_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/cv4001

SRCS := $(DIR)/cv4001/cv4001.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

