MODULE_NAME := sensor_ar1337_t31
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/ar1337

SRCS := $(DIR)/ar1337/ar1337.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

