MODULE_NAME := sensor_ps5270_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/ps5270

SRCS := $(DIR)/ps5270/ps5270.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

