MODULE_NAME := sensor_ov01a1s_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/ov01a1s

SRCS := $(DIR)/ov01a1s/ov01a1s.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

