MODULE_NAME := sensor_sc2331_t23
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc2331

SRCS := $(DIR)/sc2331/sc2331.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
