MODULE_NAME := sensor_sc301iot_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc301iot

SRCS := $(DIR)/sc301iot/sc301iot.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

