MODULE_NAME := sensor_os08a10_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/os08a10

SRCS := $(DIR)/os08a10/os08a10.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

