MODULE_NAME := sensor_ov9732_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/ov9732

SRCS := $(DIR)/ov9732/ov9732.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

