MODULE_NAME := sensor_ov7251_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/ov7251

SRCS := $(DIR)/ov7251/ov7251.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

