MODULE_NAME := sensor_jxf38p_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/jxf38p

SRCS := $(DIR)/jxf38p/jxf38p.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

