MODULE_NAME := sensor_bf3a03_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/bf3a03

SRCS := $(DIR)/bf3a03/bf3a03.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

