MODULE_NAME := sensor_sc2235_t41
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/sc2235

SRCS := $(DIR)/sc2235/sc2235.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

