MODULE_NAME := sensor_jxf51_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/jxf51

SRCS := $(DIR)/jxf51/jxf51.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

